In [5]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [6]:
dataset=pd.read_csv("CKD.csv")

In [8]:
dataset

age         bp sg  al  su     rbc        pc         pcc  \
0     2.000000  76.459948  c   3   0  normal  abnormal  notpresent   
1     3.000000  76.459948  c   2   0  normal    normal  notpresent   
2     4.000000  76.459948  a   1   0  normal    normal  notpresent   
3     5.000000  76.459948  d   1   0  normal    normal  notpresent   
4     5.000000  50.000000  c   0   0  normal    normal  notpresent   
..         ...        ... ..  ..  ..     ...       ...         ...   
394  51.492308  70.000000  a   0   0  normal    normal  notpresent   
395  51.492308  70.000000  c   0   2  normal    normal  notpresent   
396  51.492308  70.000000  c   3   0  normal    normal  notpresent   
397  51.492308  90.000000  a   0   0  normal    normal  notpresent   
398  51.492308  80.000000  a   0   0  normal    normal  notpresent   

             ba         bgr  ...        pcv            wc        rc  htn   dm  \
0    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
1    notpresent  148.112676  ...  34.000000  12300.000000  4.705597   no   no   
2    notpresent   99.000000  ...  34.000000   8408.191126  4.705597   no   no   
3    notpresent  148.112676  ...  38.868902   8408.191126  4.705597   no   no   
4    notpresent  148.112676  ...  36.000000  12400.000000  4.705597   no   no   
..          ...         ...  ...        ...           ...       ...  ...  ...   
394  notpresent  219.000000  ...  37.000000   9800.000000  4.400000   no   no   
395  notpresent  220.000000  ...  27.000000   8408.191126  4.705597  yes  yes   
396  notpresent  110.000000  ...  26.000000   9200.000000  3.400000  yes  yes   
397  notpresent  207.000000  ...  38.868902   8408.191126  4.705597  yes  yes   
398  notpresent  100.000000  ...  53.000000   8500.000000  4.900000   no   no   

     cad  appet    pe  ane classification  
0     no    yes   yes   no            yes  
1     no    yes  poor   no            yes  
2     no    yes  poor   no            yes  
3     no    yes  poor  yes            yes  
4     no    yes  poor   no            yes  
..   ...    ...   ...  ...            ...  
394   no    yes  poor   no            yes  
395   no    yes  poor  yes            yes  
396   no   poor  poor   no            yes  
397   no    yes  poor  yes            yes  
398   no    yes  poor   no             no  

[399 rows x 25 columns]

In [11]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [13]:
dataset=dataset.astype(int)

In [15]:
dataset

age  bp  al  su  bgr   bu  sc  sod  pot  hrmo  ...  pc_normal  \
0      2  76   3   0  148   57   3  137    4    12  ...          0   
1      3  76   2   0  148   22   0  137    4    10  ...          1   
2      4  76   1   0   99   23   0  138    4    12  ...          1   
3      5  76   1   0  148   16   0  138    3     8  ...          1   
4      5  50   0   0  148   25   0  137    4    11  ...          1   
..   ...  ..  ..  ..  ...  ...  ..  ...  ...   ...  ...        ...   
394   51  70   0   0  219   36   1  139    3    12  ...          1   
395   51  70   0   2  220   68   2  137    4     8  ...          1   
396   51  70   3   0  110  115   6  134    2     9  ...          1   
397   51  90   0   0  207   80   6  142    5     8  ...          1   
398   51  80   0   0  100   49   1  140    5    16  ...          1   

     pcc_present  ba_present  htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  \
0              0           0        0       0        0          1       1   
1              0           0        0       0        0          1       0   
2              0           0        0       0        0          1       0   
3              0           0        0       0        0          1       0   
4              0           0        0       0        0          1       0   
..           ...         ...      ...     ...      ...        ...     ...   
394            0           0        0       0        0          1       0   
395            0           0        1       1        0          1       0   
396            0           0        1       1        0          0       0   
397            0           0        1       1        0          1       0   
398            0           0        0       0        0          1       0   

     ane_yes  classification_yes  
0          0                   1  
1          0                   1  
2          0                   1  
3          1                   1  
4          0                   1  
..       ...                 ...  
394        0                   1  
395        1                   1  
396        0                   1  
397        1                   1  
398        0                   0  

[399 rows x 28 columns]

In [17]:
print(dataset.dtypes)

age                   int32
bp                    int32
al                    int32
su                    int32
bgr                   int32
bu                    int32
sc                    int32
sod                   int32
pot                   int32
hrmo                  int32
pcv                   int32
wc                    int32
rc                    int32
sg_b                  int32
sg_c                  int32
sg_d                  int32
sg_e                  int32
rbc_normal            int32
pc_normal             int32
pcc_present           int32
ba_present            int32
htn_yes               int32
dm_yes                int32
cad_yes               int32
appet_yes             int32
pe_yes                int32
ane_yes               int32
classification_yes    int32
dtype: object


In [19]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [21]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [23]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv','wc', 'rc','sg_b', 'sg_c', 'sg_d', 'sg_e','rbc_normal', 'pc_normal','pcc_present',  'ba_present', 'htn_yes','dm_yes','cad_yes',  'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset['classification_yes']

In [25]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(indep, dep, test_size = 0.1, random_state = 42)

In [27]:
from sklearn.naive_bayes import BernoulliNB
from sklearn.model_selection import GridSearchCV
param_grid = {'alpha':[0.1,0.01,1.0,5.0],'binarize':[0.0,0.1,0.5,1.0,2.0]}
grid = GridSearchCV(BernoulliNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
grid.fit(X_train, y_train) 

Fitting 5 folds for each of 20 candidates, totalling 100 fits


GridSearchCV(estimator=BernoulliNB(), n_jobs=-1,
             param_grid={'alpha': [0.1, 0.01, 1.0, 5.0],
                         'binarize': [0.0, 0.1, 0.5, 1.0, 2.0]},
             scoring='f1_weighted', verbose=3)

In [28]:
re=grid.cv_results_
grid_predictions = grid.predict(X_test) 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)
print("The confusion Matrix:\n",cm)
print("The report:\n",clf_report)

The f1_macro value for best parameter {'alpha': 0.01, 'binarize': 0.0}: 0.925046904315197
The confusion Matrix:
 [[18  1]
 [ 2 19]]
The report:
               precision    recall  f1-score   support

           0       0.90      0.95      0.92        19
           1       0.95      0.90      0.93        21

    accuracy                           0.93        40
   macro avg       0.93      0.93      0.92        40
weighted avg       0.93      0.93      0.93        40



In [29]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_alpha  \
0        0.004203      0.001212         0.049240        0.006231         0.10   
1        0.003702      0.000984         0.026723        0.011531         0.10   
2        0.004406      0.002134         0.006905        0.005613         0.10   
3        0.002800      0.000400         0.002804        0.000512         0.10   
4        0.002708      0.000681         0.002599        0.000489         0.10   
5        0.002801      0.000749         0.002802        0.000400         0.01   
6        0.003002      0.000633         0.002600        0.000490         0.01   
7        0.002400      0.000490         0.002604        0.000373         0.01   
8        0.002305      0.000509         0.002104        0.000203         0.01   
9        0.002201      0.000400         0.002600        0.000490         0.01   
10       0.002200      0.000400         0.002425        0.000522         1.00   
11       0.002098      0.000049         0.002424        0.000521         1.00   
12       0.001800      0.000400         0.002501        0.000447         1.00   
13       0.002603      0.000585         0.002905        0.001114         1.00   
14       0.002201      0.000399         0.002501        0.000447         1.00   
15       0.002002      0.000003         0.003005        0.000316         5.00   
16       0.002604      0.000587         0.002401        0.000489         5.00   
17       0.002200      0.000400         0.002603        0.000374         5.00   
18       0.002405      0.000666         0.001903        0.000200         5.00   
19       0.002001      0.000003         0.002200        0.000400         5.00   

    param_binarize                            params  split0_test_score  \
0              0.0   {'alpha': 0.1, 'binarize': 0.0}           0.986159   
1              0.1   {'alpha': 0.1, 'binarize': 0.1}           0.986159   
2              0.5   {'alpha': 0.1, 'binarize': 0.5}           0.986159   
3              1.0   {'alpha': 0.1, 'binarize': 1.0}           0.876984   
4              2.0   {'alpha': 0.1, 'binarize': 2.0}           0.735144   
5              0.0  {'alpha': 0.01, 'binarize': 0.0}           0.986159   
6              0.1  {'alpha': 0.01, 'binarize': 0.1}           0.986159   
7              0.5  {'alpha': 0.01, 'binarize': 0.5}           0.986159   
8              1.0  {'alpha': 0.01, 'binarize': 1.0}           0.876984   
9              2.0  {'alpha': 0.01, 'binarize': 2.0}           0.735144   
10             0.0   {'alpha': 1.0, 'binarize': 0.0}           0.904256   
11             0.1   {'alpha': 1.0, 'binarize': 0.1}           0.904256   
12             0.5   {'alpha': 1.0, 'binarize': 0.5}           0.904256   
13             1.0   {'alpha': 1.0, 'binarize': 1.0}           0.876984   
14             2.0   {'alpha': 1.0, 'binarize': 2.0}           0.735144   
15             0.0   {'alpha': 5.0, 'binarize': 0.0}           0.904256   
16             0.1   {'alpha': 5.0, 'binarize': 0.1}           0.904256   
17             0.5   {'alpha': 5.0, 'binarize': 0.5}           0.904256   
18             1.0   {'alpha': 5.0, 'binarize': 1.0}           0.876984   
19             2.0   {'alpha': 5.0, 'binarize': 2.0}           0.480769   

    split1_test_score  split2_test_score  split3_test_score  \
0            1.000000           0.986166           1.000000   
1            1.000000           0.986166           1.000000   
2            1.000000           0.986166           1.000000   
3            0.917284           0.836612           0.877268   
4            0.809380           0.679261           0.795359   
5            1.000000           1.000000           1.000000   
6            1.000000           1.000000           1.000000   
7            1.000000           1.000000           1.000000   
8            0.917284           0.836612           0.877268   
9            0.809380           0.679261           0.795359   
10           0.986166           0

In [83]:
from sklearn.naive_bayes import CategoricalNB
from sklearn.model_selection import GridSearchCV
param_grid = {'alpha':[0.1,1.0,5.0,10.0]}
grid = GridSearchCV(CategoricalNB(), param_grid,cv=2, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
grid.fit(X_train, y_train) 

Fitting 2 folds for each of 4 candidates, totalling 8 fits


C:\Anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1108: UserWarning: One or more of the test scores are non-finite: [nan nan nan nan]
  warnings.warn(


GridSearchCV(cv=2, estimator=CategoricalNB(), n_jobs=-1,
             param_grid={'alpha': [0.1, 1.0, 5.0, 10.0]}, scoring='f1_weighted',
             verbose=3)

In [85]:
re=grid.cv_results_
grid_predictions = grid.predict(X_test) 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)
print("The confusion Matrix:\n",cm)
print("The report:\n",clf_report)

The f1_macro value for best parameter {'alpha': 0.1}: 1.0
The confusion Matrix:
 [[19  0]
 [ 0 21]]
The report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        21

    accuracy                           1.00        40
   macro avg       1.00      1.00      1.00        40
weighted avg       1.00      1.00      1.00        40



In [89]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_alpha  \
0       0.003273      0.000250         0.001006        0.000502          0.1   
1       0.003271      0.000252         0.001259        0.000252          1.0   
2       0.003513      0.000000         0.031519        0.000000          5.0   
3       0.004013      0.000500         0.031519        0.000000         10.0   

            params  split0_test_score  split1_test_score  mean_test_score  \
0   {'alpha': 0.1}                NaN                NaN              NaN   
1   {'alpha': 1.0}                NaN                NaN              NaN   
2   {'alpha': 5.0}                NaN                NaN              NaN   
3  {'alpha': 10.0}                NaN                NaN              NaN   

   std_test_score  rank_test_score  
0             NaN                1  
1             NaN                1  
2             NaN                1  
3             NaN                1

In [91]:
from sklearn.naive_bayes import ComplementNB
from sklearn.model_selection import GridSearchCV
param_grid = {'alpha':[0.1,1.0,0.5]}
grid = GridSearchCV(ComplementNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
grid.fit(X_train, y_train) 

Fitting 5 folds for each of 3 candidates, totalling 15 fits


GridSearchCV(estimator=ComplementNB(), n_jobs=-1,
             param_grid={'alpha': [0.1, 1.0, 0.5]}, scoring='f1_weighted',
             verbose=3)

In [93]:
re=grid.cv_results_
grid_predictions = grid.predict(X_test) 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)
print("The confusion Matrix:\n",cm)
print("The report:\n",clf_report)

The f1_macro value for best parameter {'alpha': 0.1}: 0.8994987468671679
The confusion Matrix:
 [[19  0]
 [ 4 17]]
The report:
               precision    recall  f1-score   support

           0       0.83      1.00      0.90        19
           1       1.00      0.81      0.89        21

    accuracy                           0.90        40
   macro avg       0.91      0.90      0.90        40
weighted avg       0.92      0.90      0.90        40



In [33]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.93734335839599

In [35]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_alpha  \
0       0.002349      0.000599         0.002509        0.000439          0.1   
1       0.002505      0.000447         0.002997        0.000335          1.0   
2       0.002598      0.000597         0.002425        0.000472          0.5   

           params  split0_test_score  split1_test_score  split2_test_score  \
0  {'alpha': 0.1}           0.863281           0.890332           0.891005   
1  {'alpha': 1.0}           0.835664           0.863450           0.836458   
2  {'alpha': 0.5}           0.835664           0.863450           0.850186   

   split3_test_score  split4_test_score  mean_test_score  std_test_score  \
0           0.931279           0.889128         0.893005        0.021793   
1           0.917749           0.820139         0.854692        0.034471   
2           0.917749           0.847892         0.862988        0.028766   

   rank_test_score  
0                1  
1                3  
2                2

In [37]:
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV
param_grid = {'var_smoothing':[1e-09,1e-06,1e-03 ]}
grid = GridSearchCV(GaussianNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
grid.fit(X_train, y_train) 

Fitting 5 folds for each of 3 candidates, totalling 15 fits


GridSearchCV(estimator=GaussianNB(), n_jobs=-1,
             param_grid={'var_smoothing': [1e-09, 1e-06, 0.001]},
             scoring='f1_weighted', verbose=3)

In [39]:
re=grid.cv_results_
grid_predictions = grid.predict(X_test) 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)
print("The confusion Matrix:\n",cm)
print("The report:\n",clf_report)

The f1_macro value for best parameter {'var_smoothing': 1e-09}: 0.925046904315197
The confusion Matrix:
 [[18  1]
 [ 2 19]]
The report:
               precision    recall  f1-score   support

           0       0.90      0.95      0.92        19
           1       0.95      0.90      0.93        21

    accuracy                           0.93        40
   macro avg       0.93      0.93      0.92        40
weighted avg       0.93      0.93      0.93        40



In [41]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9711779448621555

In [43]:
table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0       0.003602      0.000735         0.004103        0.001498   
1       0.003105      0.000377         0.002702        0.000598   
2       0.003203      0.000680         0.003203        0.000510   

   param_var_smoothing                    params  split0_test_score  \
0         1.000000e-09  {'var_smoothing': 1e-09}           0.986159   
1         1.000000e-06  {'var_smoothing': 1e-06}           0.821719   
2         1.000000e-03  {'var_smoothing': 0.001}           0.704783   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           1.000000           1.000000           1.000000           0.985969   
1           0.863843           0.850186           0.877444           0.889339   
2           0.668983           0.712573           0.672106           0.639965   

   mean_test_score  std_test_score  rank_test_score  
0         0.994426        0.006827                1  
1         0.860506        0.023411                2  
2         0.679682        0.026310                3

In [53]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import GridSearchCV
param_grid = {'alpha':[0.1,0.5,1.0,5.0]}
grid = GridSearchCV(MultinomialNB(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
grid.fit(X_train, y_train) 

Fitting 5 folds for each of 4 candidates, totalling 20 fits


GridSearchCV(estimator=MultinomialNB(), n_jobs=-1,
             param_grid={'alpha': [0.1, 0.5, 1.0, 5.0]}, scoring='f1_weighted',
             verbose=3)

In [55]:
re=grid.cv_results_
grid_predictions = grid.predict(X_test) 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)
print("The confusion Matrix:\n",cm)
print("The report:\n",clf_report)

The f1_macro value for best parameter {'alpha': 0.1}: 0.8994987468671679
The confusion Matrix:
 [[19  0]
 [ 4 17]]
The report:
               precision    recall  f1-score   support

           0       0.83      1.00      0.90        19
           1       1.00      0.81      0.89        21

    accuracy                           0.90        40
   macro avg       0.91      0.90      0.90        40
weighted avg       0.92      0.90      0.90        40



In [57]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.93734335839599

In [59]:
table=pd.DataFrame.from_dict(re)

In [61]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_alpha  \
0       0.002534      0.000555         0.015898        0.001163          0.1   
1       0.002442      0.000543         0.009114        0.007696          0.5   
2       0.003205      0.001293         0.003502        0.001341          1.0   
3       0.002805      0.000931         0.002198        0.000400          5.0   

           params  split0_test_score  split1_test_score  split2_test_score  \
0  {'alpha': 0.1}           0.863281           0.890332           0.891005   
1  {'alpha': 0.5}           0.835664           0.863450           0.850186   
2  {'alpha': 1.0}           0.835664           0.863450           0.836458   
3  {'alpha': 5.0}           0.807663           0.795740           0.822644   

   split3_test_score  split4_test_score  mean_test_score  std_test_score  \
0           0.931279           0.889128         0.893005        0.021793   
1           0.917749           0.847892         0.862988        0.028766   
2           0.917749           0.834053         0.857475        0.032046   
3           0.890760           0.806135         0.824588        0.034181   

   rank_test_score  
0                1  
1                2  
2                3  
3                4

In [ ]:
age_input=float(input("enter age:"))
bp_input=float(input("enter bp:"))
al_input=int(input("enter al:"))
su_input=int(input("enter su:"))
bgr_input=float(input("enter bgr:"))
bu_input=float(input("enter bu:"))
sc_input=float(input("enter sc:"))
sod_input=float(input("enter sod:"))
pot_input=float(input("enter pot:"))
hrmo_input=float(input("enter hrmo:"))
pcv_input=float(input("enter pcv:"))
wc_input=float(input("enter wc:"))
rc_input=float(input("enter rc:"))
sg_b_input=int(input("enter sg_b:"))
sg_c_input=int(input("enter sg_c:"))
sg_d_input=int(input("enter sg_d:"))
sg_e_input=int(input("enter sg_e:"))
rbc_normal_input=int(input("enter rbc_normal:"))
pc_normal_input=int(input("enter pc_normal:"))
pcc_present_input=int(input("enter pcc_present:"))
ba_present_input=int(input("enter ba_present:"))
htn_yes_input=int(input("enter htn_yes:"))
dm_yes_input=int(input("enter dm_yes:"))
cad_yes_input=int(input("enter cad_yes:"))
appet_yes_input=int(input("enter appet_yes:"))
pe_yes_input=int(input("enter pe_yes:"))
ane_yes_input=int(input("enter ane_yes:"))

In [ ]:
Future_Prediction=grid.predict([[age_input,bp_input,al_input,su_input,bgr_input,bu_input,sc_input,sod_input,pot_input,hrmo_input,pcv_input,wc_input,rc_input,sg_b_input,sg_c_input,sg_d_input,sg_e_input,rbc_normal_input, pc_normal_input,pcc_present_input, ba_present_input, htn_yes_input,dm_yes_input,cad_yes_input,appet_yes_input,pe_yes_input,ane_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))   